loglevel: Debug
write-directory: test_output
write: true
output: yaml
services:
  your-service:
    plugin: example-plugin
    policy:
      catalogs: ["OSPS_B"]
      applicability:
        - Maturity1
        - Maturity2
        - Maturity3
    vars:
      your: a
      required: x
      variables: y
